"""Minimal asynchronous repository ports owned by the domain package."""

import builtins
from datetime import date, datetime
from typing import Protocol
from uuid import UUID

from alphadesk_domain.accounting import (
    AccountReconciliationRun,
    AccountSnapshot,
    CashBalance,
    CashLedgerEntry,
    LedgerTransaction,
    PositionLedgerEntry,
)
from alphadesk_domain.ai_research import AIAnalysisRun, ResearchEvidence, ResearchInsight
from alphadesk_domain.backtest import (
    BacktestEquityPoint,
    BacktestEvent,
    BacktestMetricSet,
    BacktestRun,
    BacktestTradeSummary,
)
from alphadesk_domain.entities import (
    AuditLog,
    DomainEvent,
    ExecutorDevice,
    ExecutorDeviceAccount,
    Fill,
    Instrument,
    Order,
    OrderAction,
    OrderCommand,
    OrderStateTransition,
    OutboxMessage,
    Position,
    RiskDecision,
    RiskRuleEvaluation,
    Signal,
    Strategy,
    StrategyVersion,
    TradingAccount,
    Watchlist,
    WatchlistItem,
)
from alphadesk_domain.enums import (
    AdjustmentType,
    MarketDataIssueSeverity,
    MarketDataQualityRunStatus,
    MarketSyncStatus,
    MarketTimeframe,
    RealtimeRunStatus,
)
from alphadesk_domain.information import (
    EventInstrumentLink,
    EventThemeLink,
    InformationIngestionRun,
    InformationItem,
    InformationSource,
    MarketEvent,
    RawDocument,
)
from alphadesk_domain.market import (
    InstrumentMapping,
    MarketBar,
    MarketBarUpsertResult,
    MarketDataCoverage,
    MarketDataQualityIssue,
    MarketDataQualityRun,
    MarketDataSource,
    MarketSyncRun,
)
from alphadesk_domain.market_reference import (
    AdjustmentFactor,
    FactorConvention,
    InstrumentLifecycleEvent,
    InstrumentTradingStatus,
    TradingCalendarSession,
)
from alphadesk_domain.realtime_market import MarketRealtimeRun
from alphadesk_domain.replay import ReplayControlAction, ReplayEvent, ReplayRun
from alphadesk_domain.scanners import ScanResult, ScanRun
from alphadesk_domain.simulated_execution import BrokerExecutionAttempt
from alphadesk_domain.strategy_experiments import StrategyExperiment, StrategyExperimentRun
from alphadesk_domain.strategy_runs import StrategyRun


class InstrumentRepository(Protocol):
    async def add(self, entity: Instrument) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Instrument | None: ...
    async def get_by_business_key(self, exchange: str, symbol: str) -> Instrument | None: ...
    async def get_many(self, entity_ids: list[UUID]) -> list[Instrument]: ...
    async def search(
        self,
        *,
        keyword: str | None,
        exchange: str | None,
        market: str | None,
        asset_type: str | None,
        is_active: bool | None,
        offset: int,
        limit: int,
    ) -> tuple[list[Instrument], int]: ...
    async def upsert_many(self, entities: list[Instrument]) -> list[Instrument]: ...


class WatchlistRepository(Protocol):
    async def add(self, entity: Watchlist) -> None: ...
    async def add_item(self, entity: WatchlistItem) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Watchlist | None: ...
    async def get_by_name(self, name: str) -> Watchlist | None: ...
    async def list_all(self) -> list[Watchlist]: ...
    async def list_items(self, watchlist_id: UUID) -> list[WatchlistItem]: ...
    async def get_item(self, item_id: UUID) -> WatchlistItem | None: ...
    async def update(self, entity: Watchlist) -> None: ...
    async def update_item(self, entity: WatchlistItem) -> None: ...
    async def remove_item(self, item_id: UUID) -> None: ...
    async def reorder(self, watchlist_id: UUID, item_ids: list[UUID]) -> None: ...
    async def delete(self, watchlist_id: UUID) -> None: ...


class TradingAccountRepository(Protocol):
    async def add(self, entity: TradingAccount) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> TradingAccount | None: ...
    async def get_for_update(self, entity_id: UUID) -> TradingAccount | None: ...
    async def get_by_business_key(self, account_code: str) -> TradingAccount | None: ...
    async def get_by_creation_idempotency_key(self, key: str) -> TradingAccount | None: ...
    async def list_all(self) -> list[TradingAccount]: ...
    async def update(self, entity: TradingAccount) -> None: ...


class PositionRepository(Protocol):
    async def add(self, entity: Position) -> None: ...
    async def get_for_account_instrument(
        self, account_id: UUID, instrument_id: UUID
    ) -> Position | None: ...
    async def get_for_update(self, account_id: UUID, instrument_id: UUID) -> Position | None: ...
    async def list_for_account(self, account_id: UUID) -> list[Position]: ...
    async def update(self, entity: Position) -> None: ...


class CashBalanceRepository(Protocol):
    async def add(self, entity: CashBalance) -> None: ...
    async def get(self, account_id: UUID, currency: str) -> CashBalance | None: ...
    async def get_for_update(self, account_id: UUID, currency: str) -> CashBalance | None: ...
    async def list_for_account(self, account_id: UUID) -> list[CashBalance]: ...
    async def update(self, entity: CashBalance) -> None: ...


class LedgerTransactionRepository(Protocol):
    async def add(self, entity: LedgerTransaction) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> LedgerTransaction | None: ...
    async def get_by_business_key(self, business_key: str) -> LedgerTransaction | None: ...
    async def get_by_fill_id(self, fill_id: UUID) -> LedgerTransaction | None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[LedgerTransaction], int]: ...


class CashLedgerRepository(Protocol):
    async def append(self, entity: CashLedgerEntry) -> None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[CashLedgerEntry], int]: ...
    async def list_all_for_account(self, account_id: UUID) -> list[CashLedgerEntry]: ...
    async def get_for_transaction(self, transaction_id: UUID) -> CashLedgerEntry | None: ...


class PositionLedgerRepository(Protocol):
    async def append(self, entity: PositionLedgerEntry) -> None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[PositionLedgerEntry], int]: ...
    async def list_all_for_account(self, account_id: UUID) -> list[PositionLedgerEntry]: ...
    async def get_for_transaction(self, transaction_id: UUID) -> PositionLedgerEntry | None: ...


class AccountSnapshotRepository(Protocol):
    async def append(self, entity: AccountSnapshot) -> None: ...
    async def latest(self, account_id: UUID) -> AccountSnapshot | None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[AccountSnapshot], int]: ...


class AccountReconciliationRepository(Protocol):
    async def append(self, entity: AccountReconciliationRun) -> None: ...
    async def latest(self, account_id: UUID) -> AccountReconciliationRun | None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[AccountReconciliationRun], int]: ...


class StrategyRepository(Protocol):
    async def add(self, entity: Strategy) -> None: ...
    async def add_version(self, entity: StrategyVersion) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Strategy | None: ...
    async def get_by_business_key(self, strategy_code: str) -> Strategy | None: ...


class SignalRepository(Protocol):
    async def add(self, entity: Signal) -> None: ...
    async def append_many(self, entities: list[Signal]) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Signal | None: ...
    async def list_by_run(
        self,
        run_id: UUID,
        offset: int,
        limit: int,
        signal_type: str | None = None,
    ) -> tuple[list[Signal], int]: ...
    async def list_filtered(
        self,
        *,
        strategy_run_id: UUID | None,
        strategy_key: str | None,
        instrument_id: UUID | None,
        signal_type: str | None,
        generated_from: datetime | None,
        generated_to: datetime | None,
        offset: int,
        limit: int,
    ) -> tuple[list[Signal], int]: ...
    async def count_by_run(self, run_id: UUID) -> int: ...
    async def list_all_by_run(self, run_id: UUID) -> list[Signal]: ...


class StrategyRunRepository(Protocol):
    async def add(self, entity: StrategyRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> StrategyRun | None: ...
    async def get_by_idempotency_key(self, key: str) -> StrategyRun | None: ...
    async def update(self, entity: StrategyRun) -> None: ...
    async def list(
        self,
        *,
        strategy_key: str | None,
        status: str | None,
        instrument_id: UUID | None,
        created_from: datetime | None,
        created_to: datetime | None,
        offset: int,
        limit: int,
    ) -> tuple[list[StrategyRun], int]: ...


class ScanRunRepository(Protocol):
    async def add(self, entity: ScanRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> ScanRun | None: ...
    async def get_by_idempotency_key(self, key: str) -> ScanRun | None: ...
    async def update(self, entity: ScanRun) -> None: ...
    async def list(
        self,
        *,
        scanner_key: str | None,
        status: str | None,
        instrument_id: UUID | None,
        created_from: datetime | None,
        created_to: datetime | None,
        offset: int,
        limit: int,
    ) -> tuple[list[ScanRun], int]: ...


class ScanResultRepository(Protocol):
    async def append_many(self, entities: list[ScanResult]) -> None: ...
    async def list_by_run(self, run_id: UUID) -> list[ScanResult]: ...
    async def count_by_run(self, run_id: UUID) -> int: ...


class StrategyExperimentRepository(Protocol):
    async def add(self, entity: StrategyExperiment) -> None: ...
    async def claim(self, entity: StrategyExperiment) -> bool: ...
    async def get_by_id(self, entity_id: UUID) -> StrategyExperiment | None: ...
    async def get_by_idempotency_key(self, key: str) -> StrategyExperiment | None: ...
    async def get_for_update(self, entity_id: UUID) -> StrategyExperiment | None: ...
    async def update_status(self, entity: StrategyExperiment) -> None: ...
    async def list(
        self,
        *,
        strategy_key: str | None,
        status: str | None,
        created_from: datetime | None,
        created_to: datetime | None,
        offset: int,
        limit: int,
    ) -> tuple[list[StrategyExperiment], int]: ...


class StrategyExperimentRunRepository(Protocol):
    async def append(self, entity: StrategyExperimentRun) -> None: ...
    async def get_by_experiment_and_index(
        self, experiment_id: UUID, combination_index: int
    ) -> StrategyExperimentRun | None: ...
    async def list_by_experiment(self, experiment_id: UUID) -> list[StrategyExperimentRun]: ...
    async def count_by_experiment(self, experiment_id: UUID) -> int: ...


class OrderRepository(Protocol):
    async def add(self, entity: Order) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Order | None: ...
    async def get_by_idempotency_key(self, key: str) -> Order | None: ...
    async def get_for_update(self, entity_id: UUID) -> Order | None: ...

    async def append_transition(self, transition: OrderStateTransition) -> None: ...
    async def list(
        self,
        *,
        offset: int,
        limit: int,
        account_id: UUID | None = None,
        instrument_id: UUID | None = None,
        status: str | None = None,
        side: str | None = None,
        order_type: str | None = None,
        intent_source: str | None = None,
        created_from: datetime | None = None,
        created_to: datetime | None = None,
    ) -> tuple[builtins.list[Order], int]: ...
    async def list_expirable(self, now: datetime, limit: int) -> builtins.list[Order]: ...
    async def list_recent_timestamps(
        self, account_id: UUID, since: datetime
    ) -> builtins.list[datetime]: ...
    async def count_open(self, account_id: UUID) -> int: ...
    async def list_all_by_account(self, account_id: UUID) -> builtins.list[Order]: ...
    async def update_projection(self, entity: Order) -> None: ...


class OrderActionRepository(Protocol):
    async def append(self, entity: OrderAction) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> OrderAction | None: ...
    async def get_by_idempotency_key(self, key: str) -> OrderAction | None: ...
    async def list_by_order(self, order_id: UUID) -> list[OrderAction]: ...


class OrderStateTransitionRepository(Protocol):
    async def append(self, entity: OrderStateTransition) -> None: ...
    async def list_by_order(self, order_id: UUID) -> list[OrderStateTransition]: ...
    async def get_latest_by_order(self, order_id: UUID) -> OrderStateTransition | None: ...


class OrderCommandRepository(Protocol):
    async def add(self, entity: OrderCommand) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> OrderCommand | None: ...
    async def get_by_command_id(self, command_id: UUID) -> OrderCommand | None: ...
    async def get_submit_command_by_order(self, order_id: UUID) -> OrderCommand | None: ...
    async def get_submit_command_for_update(self, order_id: UUID) -> OrderCommand | None: ...
    async def list_by_order(self, order_id: UUID) -> list[OrderCommand]: ...
    async def count_submit_by_order(self, order_id: UUID) -> int: ...
    async def update(self, entity: OrderCommand) -> None: ...


class FillRepository(Protocol):
    async def append(self, entity: Fill) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Fill | None: ...
    async def list_by_order(self, order_id: UUID) -> list[Fill]: ...
    async def list_by_execution_attempt(self, attempt_id: UUID) -> list[Fill]: ...
    async def list(
        self,
        *,
        offset: int,
        limit: int,
        account_id: UUID | None = None,
        instrument_id: UUID | None = None,
        order_id: UUID | None = None,
        side: str | None = None,
        executed_from: datetime | None = None,
        executed_to: datetime | None = None,
    ) -> tuple[builtins.list[Fill], int]: ...
    async def list_all_by_account(self, account_id: UUID) -> builtins.list[Fill]: ...


class BrokerExecutionAttemptRepository(Protocol):
    async def lock_idempotency_key(self, key: str) -> None: ...
    async def add(self, entity: BrokerExecutionAttempt) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> BrokerExecutionAttempt | None: ...
    async def get_by_idempotency_key(self, key: str) -> BrokerExecutionAttempt | None: ...
    async def get_for_update(self, entity_id: UUID) -> BrokerExecutionAttempt | None: ...
    async def list_by_order(self, order_id: UUID) -> list[BrokerExecutionAttempt]: ...
    async def get_latest_by_order(self, order_id: UUID) -> BrokerExecutionAttempt | None: ...
    async def next_attempt_number(self, order_id: UUID) -> int: ...


class RiskDecisionRepository(Protocol):
    async def lock_idempotency_key(self, key: str) -> None: ...
    async def append(self, entity: RiskDecision) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> RiskDecision | None: ...
    async def get_by_idempotency_key(self, key: str) -> RiskDecision | None: ...
    async def list(
        self,
        *,
        offset: int,
        limit: int,
        account_id: UUID | None = None,
        instrument_id: UUID | None = None,
        source_type: str | None = None,
        source_id: UUID | None = None,
        decision: str | None = None,
        order_id: UUID | None = None,
        has_order: bool | None = None,
        evaluated_from: datetime | None = None,
        evaluated_to: datetime | None = None,
    ) -> tuple[builtins.list[RiskDecision], int]: ...
    async def list_all_by_account(self, account_id: UUID) -> builtins.list[RiskDecision]: ...


class RiskRuleEvaluationRepository(Protocol):
    async def append(self, entity: RiskRuleEvaluation) -> None: ...
    async def list_by_decision(self, risk_decision_id: UUID) -> list[RiskRuleEvaluation]: ...


class DomainEventRepository(Protocol):
    async def append(self, entity: DomainEvent) -> None: ...
    async def get_by_event_id(self, event_id: UUID) -> DomainEvent | None: ...
    async def list_by_entity(self, entity_type: str, entity_id: UUID) -> list[DomainEvent]: ...


class AuditLogRepository(Protocol):
    async def append(self, entity: AuditLog) -> None: ...
    async def list_by_resource(self, resource_type: str, resource_id: UUID) -> list[AuditLog]: ...


class OutboxRepository(Protocol):
    async def add(self, entity: OutboxMessage) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> OutboxMessage | None: ...
    async def get_by_event_and_topic(self, event_id: UUID, topic: str) -> OutboxMessage | None: ...
    async def get_submit_for_order_for_update(self, order_id: UUID) -> OutboxMessage | None: ...
    async def update(self, entity: OutboxMessage) -> None: ...
    async def list_pending(self, limit: int) -> list[OutboxMessage]: ...
    async def count_pending(self) -> int: ...
    async def list_by_aggregate(
        self, aggregate_type: str, aggregate_id: UUID
    ) -> list[OutboxMessage]: ...


class ExecutorDeviceRepository(Protocol):
    async def add(self, entity: ExecutorDevice) -> None: ...
    async def bind_account(self, entity: ExecutorDeviceAccount) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> ExecutorDevice | None: ...
    async def get_by_device_code(self, device_code: str) -> ExecutorDevice | None: ...


class MarketDataSourceRepository(Protocol):
    async def add(self, entity: MarketDataSource) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> MarketDataSource | None: ...
    async def get_by_code(self, source_code: str) -> MarketDataSource | None: ...
    async def list_active(self) -> list[MarketDataSource]: ...
    async def list_all(self) -> list[MarketDataSource]: ...


class InstrumentMappingRepository(Protocol):
    async def add(self, entity: InstrumentMapping) -> None: ...
    async def upsert_many(self, entities: list[InstrumentMapping]) -> None: ...
    async def get_by_source_and_external_symbol(
        self, source_id: UUID, external_symbol: str
    ) -> InstrumentMapping | None: ...
    async def get_by_source_and_instrument(
        self, source_id: UUID, instrument_id: UUID
    ) -> InstrumentMapping | None: ...
    async def list_for_instrument(self, instrument_id: UUID) -> list[InstrumentMapping]: ...
    async def list_for_source_symbols(
        self, source_id: UUID, external_symbols: list[str]
    ) -> list[InstrumentMapping]: ...


class MarketBarRepository(Protocol):
    async def upsert_many(self, entities: list[MarketBar]) -> MarketBarUpsertResult: ...
    async def get_bars(
        self,
        *,
        instrument_id: UUID,
        source_id: UUID,
        timeframe: MarketTimeframe,
        adjustment_type: AdjustmentType,
        start: datetime,
        end: datetime,
        limit: int,
    ) -> list[MarketBar]: ...
    async def get_coverage(
        self,
        *,
        instrument_ids: list[UUID],
        source_id: UUID,
        timeframe: MarketTimeframe,
        adjustment_type: AdjustmentType,
    ) -> list[MarketDataCoverage]: ...
    async def get_latest_bar(
        self,
        *,
        instrument_id: UUID,
        source_id: UUID,
        timeframe: MarketTimeframe,
        adjustment_type: AdjustmentType,
    ) -> MarketBar | None: ...
    async def get_latest_for_instruments(
        self,
        *,
        instrument_ids: list[UUID],
        source_id: UUID,
        timeframe: MarketTimeframe,
        adjustment_type: AdjustmentType,
    ) -> list[MarketBar]: ...


class MarketSyncRunRepository(Protocol):
    async def add(self, entity: MarketSyncRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> MarketSyncRun | None: ...
    async def list_recent(self, limit: int) -> list[MarketSyncRun]: ...
    async def get_by_operation_key(self, operation_key: str) -> MarketSyncRun | None: ...
    async def update_status(
        self,
        entity_id: UUID,
        *,
        status: MarketSyncStatus,
        completed_at: datetime,
        total_received: int,
        total_inserted: int,
        total_updated: int,
        total_rejected: int,
        error_summary: str | None,
        metadata: dict[str, object] | None = None,
    ) -> None: ...


class MarketDataQualityRunRepository(Protocol):
    async def add(self, entity: MarketDataQualityRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> MarketDataQualityRun | None: ...
    async def list_recent(
        self, *, offset: int, limit: int
    ) -> tuple[list[MarketDataQualityRun], int]: ...
    async def complete(
        self,
        entity_id: UUID,
        *,
        status: MarketDataQualityRunStatus,
        completed_at: datetime,
        instruments_checked: int,
        bars_checked: int,
        error_count: int,
        warning_count: int,
        info_count: int,
        metadata: dict[str, object],
    ) -> None: ...


class MarketDataQualityIssueRepository(Protocol):
    async def add_many(self, entities: list[MarketDataQualityIssue]) -> None: ...
    async def list_for_run(
        self,
        quality_run_id: UUID,
        *,
        offset: int,
        limit: int,
        severity: MarketDataIssueSeverity | None = None,
        issue_type: str | None = None,
        instrument_id: UUID | None = None,
    ) -> tuple[list[MarketDataQualityIssue], int]: ...
    async def count_by_severity(
        self, quality_run_id: UUID
    ) -> dict[MarketDataIssueSeverity, int]: ...


class MarketRealtimeRunRepository(Protocol):
    async def add(self, entity: MarketRealtimeRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> MarketRealtimeRun | None: ...
    async def list_recent(self, limit: int) -> list[MarketRealtimeRun]: ...
    async def complete(
        self,
        entity_id: UUID,
        *,
        status: RealtimeRunStatus,
        completed_at: datetime,
        received_count: int,
        changed_count: int,
        rejected_count: int,
        error_summary: str | None,
    ) -> None: ...


class InformationSourceRepository(Protocol):
    async def add(self, entity: InformationSource) -> None: ...
    async def update(self, entity: InformationSource) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> InformationSource | None: ...
    async def get_by_key(self, source_key: str) -> InformationSource | None: ...
    async def list_all(self) -> list[InformationSource]: ...


class RawDocumentRepository(Protocol):
    async def add(self, entity: RawDocument) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> RawDocument | None: ...
    async def get_by_source_external(
        self, source_id: UUID, external_id: str
    ) -> RawDocument | None: ...
    async def get_by_hash(self, content_hash: str) -> RawDocument | None: ...


class InformationItemRepository(Protocol):
    async def add(self, entity: InformationItem) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> InformationItem | None: ...
    async def get_by_raw_document(self, raw_document_id: UUID) -> InformationItem | None: ...
    async def list(
        self,
        *,
        search: str | None,
        source_id: UUID | None,
        instrument_id: UUID | None,
        theme_key: str | None,
        offset: int,
        limit: int,
    ) -> tuple[list[InformationItem], int]: ...


class MarketEventRepository(Protocol):
    async def add(self, entity: MarketEvent) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> MarketEvent | None: ...
    async def get_by_information_item(self, item_id: UUID) -> MarketEvent | None: ...
    async def list(
        self,
        *,
        event_type: str | None,
        direction: str | None,
        instrument_id: UUID | None,
        theme_key: str | None,
        search: str | None,
        offset: int,
        limit: int,
    ) -> tuple[list[MarketEvent], int]: ...


class EventInstrumentLinkRepository(Protocol):
    async def append_many(self, entities: list[EventInstrumentLink]) -> None: ...
    async def list_by_event(self, event_id: UUID) -> list[EventInstrumentLink]: ...


class EventThemeLinkRepository(Protocol):
    async def append_many(self, entities: list[EventThemeLink]) -> None: ...
    async def list_by_event(self, event_id: UUID) -> list[EventThemeLink]: ...


class InformationIngestionRunRepository(Protocol):
    async def add(self, entity: InformationIngestionRun) -> None: ...
    async def update(self, entity: InformationIngestionRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> InformationIngestionRun | None: ...


class AIAnalysisRunRepository(Protocol):
    async def add(self, entity: AIAnalysisRun) -> None: ...
    async def update(self, entity: AIAnalysisRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> AIAnalysisRun | None: ...
    async def get_by_idempotency_key(self, key: str) -> AIAnalysisRun | None: ...
    async def list(
        self,
        *,
        analysis_type: str | None,
        status: str | None,
        offset: int,
        limit: int,
    ) -> tuple[list[AIAnalysisRun], int]: ...


class ResearchInsightRepository(Protocol):
    async def append(self, entity: ResearchInsight) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> ResearchInsight | None: ...
    async def get_by_run(self, run_id: UUID) -> ResearchInsight | None: ...
    async def list(self, *, offset: int, limit: int) -> tuple[list[ResearchInsight], int]: ...


class ResearchEvidenceRepository(Protocol):
    async def append_many(self, entities: list[ResearchEvidence]) -> None: ...
    async def list_by_insight(self, insight_id: UUID) -> list[ResearchEvidence]: ...


class BacktestRunRepository(Protocol):
    async def lock_idempotency_key(self, key: str) -> None: ...
    async def add(self, entity: BacktestRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> BacktestRun | None: ...
    async def get_by_idempotency_key(self, key: str) -> BacktestRun | None: ...
    async def get_for_update(self, entity_id: UUID) -> BacktestRun | None: ...
    async def update_status(self, entity: BacktestRun) -> None: ...
    async def list(
        self, *, status: str | None, offset: int, limit: int
    ) -> tuple[list[BacktestRun], int]: ...


class BacktestEquityPointRepository(Protocol):
    async def append(self, entity: BacktestEquityPoint) -> None: ...
    async def list_by_run(self, run_id: UUID) -> list[BacktestEquityPoint]: ...
    async def get_latest(self, run_id: UUID) -> BacktestEquityPoint | None: ...
    async def count_by_run(self, run_id: UUID) -> int: ...


class BacktestMetricRepository(Protocol):
    async def save(self, entity: BacktestMetricSet) -> None: ...
    async def get_by_run(self, run_id: UUID) -> BacktestMetricSet | None: ...


class BacktestTradeSummaryRepository(Protocol):
    async def append_many(self, entities: list[BacktestTradeSummary]) -> None: ...
    async def list_by_run(self, run_id: UUID) -> list[BacktestTradeSummary]: ...


class BacktestEventRepository(Protocol):
    async def append(self, entity: BacktestEvent) -> None: ...
    async def list_by_run(self, run_id: UUID) -> list[BacktestEvent]: ...


class ReplayRunRepository(Protocol):
    async def lock_idempotency_key(self, key: str) -> None: ...
    async def add(self, entity: ReplayRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> ReplayRun | None: ...
    async def get_by_idempotency_key(self, key: str) -> ReplayRun | None: ...
    async def get_for_update(self, entity_id: UUID) -> ReplayRun | None: ...
    async def update(self, entity: ReplayRun) -> None: ...
    async def list(
        self, *, status: str | None, offset: int, limit: int
    ) -> tuple[list[ReplayRun], int]: ...
    async def list_runnable(self, now: datetime, limit: int) -> builtins.list[ReplayRun]: ...
    async def acquire_lease(
        self, entity_id: UUID, owner: str, now: datetime, expires_at: datetime
    ) -> bool: ...


class ReplayControlActionRepository(Protocol):
    async def append(self, entity: ReplayControlAction) -> None: ...
    async def get_by_idempotency_key(
        self, replay_run_id: UUID, key: str
    ) -> ReplayControlAction | None: ...
    async def list_by_run(self, replay_run_id: UUID) -> list[ReplayControlAction]: ...


class ReplayEventRepository(Protocol):
    async def append(self, entity: ReplayEvent) -> None: ...
    async def next_sequence(self, replay_run_id: UUID) -> int: ...
    async def list_by_run(
        self,
        replay_run_id: UUID,
        *,
        after_sequence: int = 0,
        event_type: str | None = None,
        instrument_id: UUID | None = None,
        offset: int = 0,
        limit: int = 100,
    ) -> tuple[list[ReplayEvent], int]: ...


class ReplayEquityPointRepository(Protocol):
    async def append(self, entity: BacktestEquityPoint) -> None: ...
    async def list_by_run(self, run_id: UUID) -> list[BacktestEquityPoint]: ...


class TradingCalendarRepository(Protocol):
    async def upsert_many(self, entities: list[TradingCalendarSession]) -> int: ...
    async def list(
        self, *, exchange: str | None, start: date | None, end: date | None, limit: int
    ) -> list[TradingCalendarSession]: ...


class AdjustmentFactorRepository(Protocol):
    async def upsert_many(self, entities: list[AdjustmentFactor]) -> int: ...
    async def list(
        self,
        *,
        instrument_ids: list[UUID] | None,
        start: date | None,
        end: date | None,
        source: str | None,
        convention: FactorConvention | None,
        limit: int,
    ) -> list[AdjustmentFactor]: ...


class InstrumentTradingStatusRepository(Protocol):
    async def upsert_many(self, entities: list[InstrumentTradingStatus]) -> int: ...
    async def list(
        self,
        *,
        instrument_ids: list[UUID] | None,
        start: date | None,
        end: date | None,
        limit: int,
    ) -> list[InstrumentTradingStatus]: ...


class InstrumentLifecycleRepository(Protocol):
    async def upsert_many(self, entities: list[InstrumentLifecycleEvent]) -> int: ...
    async def list(
        self, *, instrument_ids: list[UUID] | None, limit: int
    ) -> list[InstrumentLifecycleEvent]: ...
