"""Minimal asynchronous repository ports owned by the domain package."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from alphadesk_domain.accounting import (
    AccountReconciliationRun,
    AccountSnapshot,
    CashBalance,
    CashLedgerEntry,
    LedgerTransaction,
    PositionLedgerEntry,
)
from alphadesk_domain.entities import (
    AuditLog,
    DomainEvent,
    ExecutorDevice,
    ExecutorDeviceAccount,
    Fill,
    Instrument,
    Order,
    OrderCommand,
    OrderStateTransition,
    OutboxMessage,
    Position,
    RiskDecision,
    Signal,
    Strategy,
    StrategyVersion,
    TradingAccount,
    Watchlist,
    WatchlistItem,
)
from alphadesk_domain.enums import AdjustmentType, MarketSyncStatus, MarketTimeframe
from alphadesk_domain.market import (
    InstrumentMapping,
    MarketBar,
    MarketBarUpsertResult,
    MarketDataSource,
    MarketSyncRun,
)


class InstrumentRepository(Protocol):
    async def add(self, entity: Instrument) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Instrument | None: ...
    async def get_by_business_key(self, exchange: str, symbol: str) -> Instrument | None: ...
    async def get_many(self, entity_ids: list[UUID]) -> list[Instrument]: ...
    async def search(
        self,
        *,
        keyword: str | None,
        exchange: str | None,
        market: str | None,
        asset_type: str | None,
        is_active: bool | None,
        offset: int,
        limit: int,
    ) -> tuple[list[Instrument], int]: ...
    async def upsert_many(self, entities: list[Instrument]) -> list[Instrument]: ...


class WatchlistRepository(Protocol):
    async def add(self, entity: Watchlist) -> None: ...
    async def add_item(self, entity: WatchlistItem) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Watchlist | None: ...
    async def get_by_name(self, name: str) -> Watchlist | None: ...
    async def list_all(self) -> list[Watchlist]: ...
    async def list_items(self, watchlist_id: UUID) -> list[WatchlistItem]: ...
    async def get_item(self, item_id: UUID) -> WatchlistItem | None: ...
    async def update(self, entity: Watchlist) -> None: ...
    async def update_item(self, entity: WatchlistItem) -> None: ...
    async def remove_item(self, item_id: UUID) -> None: ...
    async def reorder(self, watchlist_id: UUID, item_ids: list[UUID]) -> None: ...
    async def delete(self, watchlist_id: UUID) -> None: ...


class TradingAccountRepository(Protocol):
    async def add(self, entity: TradingAccount) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> TradingAccount | None: ...
    async def get_by_business_key(self, account_code: str) -> TradingAccount | None: ...
    async def get_by_creation_idempotency_key(self, key: str) -> TradingAccount | None: ...
    async def list_all(self) -> list[TradingAccount]: ...
    async def update(self, entity: TradingAccount) -> None: ...


class PositionRepository(Protocol):
    async def add(self, entity: Position) -> None: ...
    async def get_for_account_instrument(
        self, account_id: UUID, instrument_id: UUID
    ) -> Position | None: ...
    async def get_for_update(self, account_id: UUID, instrument_id: UUID) -> Position | None: ...
    async def list_for_account(self, account_id: UUID) -> list[Position]: ...
    async def update(self, entity: Position) -> None: ...


class CashBalanceRepository(Protocol):
    async def add(self, entity: CashBalance) -> None: ...
    async def get(self, account_id: UUID, currency: str) -> CashBalance | None: ...
    async def get_for_update(self, account_id: UUID, currency: str) -> CashBalance | None: ...
    async def list_for_account(self, account_id: UUID) -> list[CashBalance]: ...
    async def update(self, entity: CashBalance) -> None: ...


class LedgerTransactionRepository(Protocol):
    async def add(self, entity: LedgerTransaction) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> LedgerTransaction | None: ...
    async def get_by_business_key(self, business_key: str) -> LedgerTransaction | None: ...
    async def get_by_fill_id(self, fill_id: UUID) -> LedgerTransaction | None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[LedgerTransaction], int]: ...


class CashLedgerRepository(Protocol):
    async def append(self, entity: CashLedgerEntry) -> None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[CashLedgerEntry], int]: ...
    async def list_all_for_account(self, account_id: UUID) -> list[CashLedgerEntry]: ...
    async def get_for_transaction(self, transaction_id: UUID) -> CashLedgerEntry | None: ...


class PositionLedgerRepository(Protocol):
    async def append(self, entity: PositionLedgerEntry) -> None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[PositionLedgerEntry], int]: ...
    async def list_all_for_account(self, account_id: UUID) -> list[PositionLedgerEntry]: ...
    async def get_for_transaction(self, transaction_id: UUID) -> PositionLedgerEntry | None: ...


class AccountSnapshotRepository(Protocol):
    async def append(self, entity: AccountSnapshot) -> None: ...
    async def latest(self, account_id: UUID) -> AccountSnapshot | None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[AccountSnapshot], int]: ...


class AccountReconciliationRepository(Protocol):
    async def append(self, entity: AccountReconciliationRun) -> None: ...
    async def latest(self, account_id: UUID) -> AccountReconciliationRun | None: ...
    async def list_for_account(
        self, account_id: UUID, offset: int, limit: int
    ) -> tuple[list[AccountReconciliationRun], int]: ...


class StrategyRepository(Protocol):
    async def add(self, entity: Strategy) -> None: ...
    async def add_version(self, entity: StrategyVersion) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Strategy | None: ...
    async def get_by_business_key(self, strategy_code: str) -> Strategy | None: ...


class SignalRepository(Protocol):
    async def add(self, entity: Signal) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Signal | None: ...


class OrderRepository(Protocol):
    async def add(self, entity: Order) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Order | None: ...
    async def get_by_idempotency_key(self, key: str) -> Order | None: ...
    async def append_transition(self, transition: OrderStateTransition) -> None: ...


class OrderCommandRepository(Protocol):
    async def add(self, entity: OrderCommand) -> None: ...
    async def get_by_command_id(self, command_id: UUID) -> OrderCommand | None: ...


class FillRepository(Protocol):
    async def append(self, entity: Fill) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> Fill | None: ...


class RiskDecisionRepository(Protocol):
    async def append(self, entity: RiskDecision) -> None: ...


class DomainEventRepository(Protocol):
    async def append(self, entity: DomainEvent) -> None: ...
    async def get_by_event_id(self, event_id: UUID) -> DomainEvent | None: ...


class AuditLogRepository(Protocol):
    async def append(self, entity: AuditLog) -> None: ...


class OutboxRepository(Protocol):
    async def add(self, entity: OutboxMessage) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> OutboxMessage | None: ...


class ExecutorDeviceRepository(Protocol):
    async def add(self, entity: ExecutorDevice) -> None: ...
    async def bind_account(self, entity: ExecutorDeviceAccount) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> ExecutorDevice | None: ...
    async def get_by_device_code(self, device_code: str) -> ExecutorDevice | None: ...


class MarketDataSourceRepository(Protocol):
    async def add(self, entity: MarketDataSource) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> MarketDataSource | None: ...
    async def get_by_code(self, source_code: str) -> MarketDataSource | None: ...
    async def list_active(self) -> list[MarketDataSource]: ...
    async def list_all(self) -> list[MarketDataSource]: ...


class InstrumentMappingRepository(Protocol):
    async def add(self, entity: InstrumentMapping) -> None: ...
    async def upsert_many(self, entities: list[InstrumentMapping]) -> None: ...
    async def get_by_source_and_external_symbol(
        self, source_id: UUID, external_symbol: str
    ) -> InstrumentMapping | None: ...
    async def get_by_source_and_instrument(
        self, source_id: UUID, instrument_id: UUID
    ) -> InstrumentMapping | None: ...
    async def list_for_instrument(self, instrument_id: UUID) -> list[InstrumentMapping]: ...
    async def list_for_source_symbols(
        self, source_id: UUID, external_symbols: list[str]
    ) -> list[InstrumentMapping]: ...


class MarketBarRepository(Protocol):
    async def upsert_many(self, entities: list[MarketBar]) -> MarketBarUpsertResult: ...
    async def get_bars(
        self,
        *,
        instrument_id: UUID,
        source_id: UUID,
        timeframe: MarketTimeframe,
        adjustment_type: AdjustmentType,
        start: datetime,
        end: datetime,
        limit: int,
    ) -> list[MarketBar]: ...
    async def get_latest_bar(
        self,
        *,
        instrument_id: UUID,
        source_id: UUID,
        timeframe: MarketTimeframe,
        adjustment_type: AdjustmentType,
    ) -> MarketBar | None: ...
    async def get_latest_for_instruments(
        self,
        *,
        instrument_ids: list[UUID],
        source_id: UUID,
        timeframe: MarketTimeframe,
        adjustment_type: AdjustmentType,
    ) -> list[MarketBar]: ...


class MarketSyncRunRepository(Protocol):
    async def add(self, entity: MarketSyncRun) -> None: ...
    async def get_by_id(self, entity_id: UUID) -> MarketSyncRun | None: ...
    async def list_recent(self, limit: int) -> list[MarketSyncRun]: ...
    async def update_status(
        self,
        entity_id: UUID,
        *,
        status: MarketSyncStatus,
        completed_at: datetime,
        total_received: int,
        total_inserted: int,
        total_updated: int,
        total_rejected: int,
        error_summary: str | None,
    ) -> None: ...
