"""domain_persistence

Revision ID: 0002_m02
Revises: 0001_m01_bootstrap
Create Date: 2026-07-15 09:02:25.971638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002_m02"
down_revision: str | None = "0001_m01_bootstrap"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=128), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_correlation", "audit_logs", ["correlation_id"], unique=False)
    op.create_index(
        "ix_audit_logs_resource_occurred",
        "audit_logs",
        ["resource_type", "resource_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "domain_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "schema_version >= 1", name=op.f("ck_domain_events_schema_version_positive")
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_domain_events")),
        sa.UniqueConstraint("sequence", name=op.f("uq_domain_events_sequence")),
    )
    op.create_index(
        "ix_domain_events_correlation", "domain_events", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_domain_events_entity_sequence",
        "domain_events",
        ["entity_type", "entity_id", "sequence"],
        unique=False,
    )
    op.create_index("ix_domain_events_event_time", "domain_events", ["event_time"], unique=False)
    op.create_table(
        "executor_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("public_key_fingerprint", sa.String(length=256), nullable=False),
        sa.Column(
            "capabilities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('REGISTERED', 'ACTIVE', 'SUSPENDED', 'REVOKED')",
            name=op.f("ck_executor_devices_device_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executor_devices")),
        sa.UniqueConstraint("device_code", name="uq_executor_devices_device_code"),
    )
    op.create_index("ix_executor_devices_status", "executor_devices", ["status"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("market", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("lot_size", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("price_tick", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("lot_size > 0", name=op.f("ck_instruments_lot_size_positive")),
        sa.CheckConstraint("price_tick > 0", name=op.f("ck_instruments_price_tick_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("exchange", "symbol", name="uq_instruments_exchange_symbol"),
    )
    op.create_index(
        "ix_instruments_market_active", "instruments", ["market", "is_active"], unique=False
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("strategy_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED')",
            name=op.f("ck_strategies_strategy_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
        sa.UniqueConstraint("strategy_code", name="uq_strategies_strategy_code"),
    )
    op.create_table(
        "trading_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("account_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("broker_type", sa.String(length=64), nullable=False),
        sa.Column("base_currency", sa.String(length=8), nullable=False),
        sa.Column("external_account_reference", sa.String(length=256), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_type IN ('SIMULATED', 'CASH', 'MARGIN')",
            name=op.f("ck_trading_accounts_account_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'READ_ONLY', 'SUSPENDED', 'CLOSED')",
            name=op.f("ck_trading_accounts_account_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_accounts")),
        sa.UniqueConstraint("account_code", name="uq_trading_accounts_account_code"),
    )
    op.create_table(
        "watchlists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlists")),
    )
    op.create_table(
        "executor_device_accounts",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("permission", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "permission IN ('READ_ONLY', 'SIMULATED', 'CONTROLLED_LIVE')",
            name=op.f("ck_executor_device_accounts_permission_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_executor_device_accounts_account_id_trading_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["executor_devices.id"],
            name=op.f("fk_executor_device_accounts_device_id_executor_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "device_id", "account_id", name=op.f("pk_executor_device_accounts")
        ),
    )
    op.create_index(
        "ix_executor_device_accounts_account",
        "executor_device_accounts",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=128), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "headers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PUBLISHED', 'FAILED')",
            name=op.f("ck_outbox_messages_outbox_status_valid"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_messages_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["domain_events.event_id"],
            name=op.f("fk_outbox_messages_event_id_domain_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint("event_id", "topic", name="uq_outbox_messages_event_topic"),
    )
    op.create_index(
        "ix_outbox_messages_aggregate",
        "outbox_messages",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_messages_pending_available",
        "outbox_messages",
        ["available_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("total_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("available_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("frozen_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("market_value", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "available_quantity + frozen_quantity <= total_quantity",
            name=op.f("ck_positions_available_frozen_within_total"),
        ),
        sa.CheckConstraint(
            "available_quantity >= 0", name=op.f("ck_positions_available_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "frozen_quantity >= 0", name=op.f("ck_positions_frozen_quantity_non_negative")
        ),
        sa.CheckConstraint("row_version >= 1", name=op.f("ck_positions_row_version_positive")),
        sa.CheckConstraint(
            "total_quantity >= 0", name=op.f("ck_positions_total_quantity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_positions_account_id_trading_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_positions_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("account_id", "instrument_id", name="uq_positions_account_instrument"),
    )
    op.create_index("ix_positions_account", "positions", ["account_id"], unique=False)
    op.create_table(
        "strategy_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.String(length=128), nullable=False),
        sa.Column("code_reference", sa.String(length=512), nullable=False),
        sa.Column(
            "parameter_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "default_parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "version_number >= 1", name=op.f("ck_strategy_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_strategy_versions_strategy_id_strategies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_versions")),
        sa.UniqueConstraint(
            "strategy_id", "version_number", name="uq_strategy_versions_strategy_version"
        ),
    )
    op.create_index(
        "uq_strategy_versions_one_active",
        "strategy_versions",
        ["strategy_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("watchlist_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sort_order >= 0", name=op.f("ck_watchlist_items_sort_order_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_watchlist_items_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlists.id"],
            name=op.f("fk_watchlist_items_watchlist_id_watchlists"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_items")),
        sa.UniqueConstraint(
            "watchlist_id", "instrument_id", name="uq_watchlist_items_watchlist_instrument"
        ),
    )
    op.create_index(
        "ix_watchlist_items_watchlist_sort",
        "watchlist_items",
        ["watchlist_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("signal_type", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("target_quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("target_weight", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("reference_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("side IN ('BUY', 'SELL')", name=op.f("ck_signals_signal_side_valid")),
        sa.CheckConstraint(
            "signal_type IN ('ENTRY', 'EXIT', 'REBALANCE', 'ADVICE')",
            name=op.f("ck_signals_signal_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('CREATED', 'EVALUATED', 'EXPIRED', 'REJECTED')",
            name=op.f("ck_signals_signal_status_valid"),
        ),
        sa.CheckConstraint(
            "target_quantity IS NULL OR target_quantity > 0",
            name=op.f("ck_signals_target_quantity_positive"),
        ),
        sa.CheckConstraint(
            "target_weight IS NULL OR (target_weight >= 0 AND target_weight <= 1)",
            name=op.f("ck_signals_target_weight_range"),
        ),
        sa.CheckConstraint("valid_until > generated_at", name=op.f("ck_signals_validity_window")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_signals_account_id_trading_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_signals_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_signals_strategy_id_strategies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_signals_strategy_version_id_strategy_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index(
        "ix_signals_account_instrument", "signals", ["account_id", "instrument_id"], unique=False
    )
    op.create_index(
        "ix_signals_strategy_generated", "signals", ["strategy_id", "generated_at"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=True),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=True),
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("time_in_force", sa.String(length=16), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("average_fill_price", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("broker_type", sa.String(length=64), nullable=False),
        sa.Column("broker_order_id", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "order_type <> 'LIMIT' OR limit_price IS NOT NULL",
            name=op.f("ck_orders_limit_order_has_price"),
        ),
        sa.CheckConstraint(
            "order_type IN ('MARKET', 'LIMIT')", name=op.f("ck_orders_order_type_valid")
        ),
        sa.CheckConstraint("side IN ('BUY', 'SELL')", name=op.f("ck_orders_order_side_valid")),
        sa.CheckConstraint(
            "status IN ('CREATED', 'RISK_CHECKING', 'RISK_REJECTED', 'WAITING_CONFIRMATION', 'QUEUED', 'DISPATCHED', 'EXECUTOR_ACCEPTED', 'EXECUTOR_REJECTED', 'BROKER_SUBMITTED', 'BROKER_ACCEPTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCEL_PENDING', 'CANCELLED', 'EXPIRED', 'FAILED', 'RECONCILIATION_REQUIRED')",
            name=op.f("ck_orders_order_status_valid"),
        ),
        sa.CheckConstraint(
            "time_in_force IN ('DAY', 'GTC', 'IOC', 'FOK')",
            name=op.f("ck_orders_time_in_force_valid"),
        ),
        sa.CheckConstraint(
            "filled_quantity <= requested_quantity", name=op.f("ck_orders_filled_within_requested")
        ),
        sa.CheckConstraint(
            "filled_quantity >= 0", name=op.f("ck_orders_filled_quantity_non_negative")
        ),
        sa.CheckConstraint(
            "limit_price IS NULL OR limit_price > 0", name=op.f("ck_orders_limit_price_positive")
        ),
        sa.CheckConstraint(
            "requested_quantity > 0", name=op.f("ck_orders_requested_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_orders_account_id_trading_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_orders_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_orders_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_orders_strategy_id_strategies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id"],
            ["strategy_versions.id"],
            name=op.f("fk_orders_strategy_version_id_strategy_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("idempotency_key", name="uq_orders_idempotency_key"),
    )
    op.create_index(
        "ix_orders_account_created", "orders", ["account_id", "created_at"], unique=False
    )
    op.create_index("ix_orders_correlation", "orders", ["correlation_id"], unique=False)
    op.create_index("ix_orders_status_created", "orders", ["status", "created_at"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("broker_type", sa.String(length=64), nullable=False),
        sa.Column("broker_fill_id", sa.String(length=128), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("commission", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("tax", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("other_fee", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("commission >= 0", name=op.f("ck_fills_commission_non_negative")),
        sa.CheckConstraint("other_fee >= 0", name=op.f("ck_fills_other_fee_non_negative")),
        sa.CheckConstraint("price > 0", name=op.f("ck_fills_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_fills_quantity_positive")),
        sa.CheckConstraint("tax >= 0", name=op.f("ck_fills_tax_non_negative")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_fills_account_id_trading_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_fills_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("broker_type", "broker_fill_id", name="uq_fills_broker_fill"),
    )
    op.create_index(
        "ix_fills_account_instrument", "fills", ["account_id", "instrument_id"], unique=False
    )
    op.create_index("ix_fills_order_executed", "fills", ["order_id", "executed_at"], unique=False)
    op.create_table(
        "order_commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("command_type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("target_device_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("signature_reference", sa.String(length=256), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "command_type IN ('SUBMIT', 'CANCEL')",
            name=op.f("ck_order_commands_command_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('CREATED', 'QUEUED', 'ACKNOWLEDGED', 'EXPIRED', 'FAILED')",
            name=op.f("ck_order_commands_command_status_valid"),
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_order_commands_expiry_after_creation")
        ),
        sa.CheckConstraint(
            "sequence_number >= 0", name=op.f("ck_order_commands_sequence_number_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_commands_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_device_id"],
            ["executor_devices.id"],
            name=op.f("fk_order_commands_target_device_id_executor_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_commands")),
        sa.UniqueConstraint("command_id", name="uq_order_commands_command_id"),
    )
    op.create_index(
        "ix_order_commands_order_sequence",
        "order_commands",
        ["order_id", "sequence_number"],
        unique=False,
    )
    op.create_index(
        "ix_order_commands_target_status",
        "order_commands",
        ["target_device_id", "status"],
        unique=False,
    )
    op.create_table(
        "order_state_transitions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("actor_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ('CREATED', 'RISK_CHECKING', 'RISK_REJECTED', 'WAITING_CONFIRMATION', 'QUEUED', 'DISPATCHED', 'EXECUTOR_ACCEPTED', 'EXECUTOR_REJECTED', 'BROKER_SUBMITTED', 'BROKER_ACCEPTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCEL_PENDING', 'CANCELLED', 'EXPIRED', 'FAILED', 'RECONCILIATION_REQUIRED')",
            name=op.f("ck_order_state_transitions_from_status_valid"),
        ),
        sa.CheckConstraint(
            "to_status IN ('CREATED', 'RISK_CHECKING', 'RISK_REJECTED', 'WAITING_CONFIRMATION', 'QUEUED', 'DISPATCHED', 'EXECUTOR_ACCEPTED', 'EXECUTOR_REJECTED', 'BROKER_SUBMITTED', 'BROKER_ACCEPTED', 'PARTIALLY_FILLED', 'FILLED', 'CANCEL_PENDING', 'CANCELLED', 'EXPIRED', 'FAILED', 'RECONCILIATION_REQUIRED')",
            name=op.f("ck_order_state_transitions_to_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_state_transitions_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_state_transitions")),
    )
    op.create_index(
        "ix_order_state_transitions_correlation",
        "order_state_transitions",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        "ix_order_state_transitions_order_occurred",
        "order_state_transitions",
        ["order_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("layer", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("rule_code", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('ALLOW', 'REJECT', 'REQUIRE_CONFIRMATION')",
            name=op.f("ck_risk_decisions_risk_decision_valid"),
        ),
        sa.CheckConstraint(
            "layer IN ('BACKEND', 'EXECUTOR')", name=op.f("ck_risk_decisions_risk_layer_valid")
        ),
        sa.CheckConstraint(
            "signal_id IS NOT NULL OR order_id IS NOT NULL",
            name=op.f("ck_risk_decisions_target_required"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_risk_decisions_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_risk_decisions_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
    )
    op.create_index(
        "ix_risk_decisions_correlation", "risk_decisions", ["correlation_id"], unique=False
    )
    op.create_index("ix_risk_decisions_order", "risk_decisions", ["order_id"], unique=False)
    op.create_index("ix_risk_decisions_signal", "risk_decisions", ["signal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_risk_decisions_signal", table_name="risk_decisions")
    op.drop_index("ix_risk_decisions_order", table_name="risk_decisions")
    op.drop_index("ix_risk_decisions_correlation", table_name="risk_decisions")
    op.drop_table("risk_decisions")
    op.drop_index("ix_order_state_transitions_order_occurred", table_name="order_state_transitions")
    op.drop_index("ix_order_state_transitions_correlation", table_name="order_state_transitions")
    op.drop_table("order_state_transitions")
    op.drop_index("ix_order_commands_target_status", table_name="order_commands")
    op.drop_index("ix_order_commands_order_sequence", table_name="order_commands")
    op.drop_table("order_commands")
    op.drop_index("ix_fills_order_executed", table_name="fills")
    op.drop_index("ix_fills_account_instrument", table_name="fills")
    op.drop_table("fills")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index("ix_orders_correlation", table_name="orders")
    op.drop_index("ix_orders_account_created", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_signals_strategy_generated", table_name="signals")
    op.drop_index("ix_signals_account_instrument", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_watchlist_items_watchlist_sort", table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index(
        "uq_strategy_versions_one_active",
        table_name="strategy_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("strategy_versions")
    op.drop_index("ix_positions_account", table_name="positions")
    op.drop_table("positions")
    op.drop_index(
        "ix_outbox_messages_pending_available",
        table_name="outbox_messages",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index("ix_outbox_messages_aggregate", table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index("ix_executor_device_accounts_account", table_name="executor_device_accounts")
    op.drop_table("executor_device_accounts")
    op.drop_table("watchlists")
    op.drop_table("trading_accounts")
    op.drop_table("strategies")
    op.drop_index("ix_instruments_market_active", table_name="instruments")
    op.drop_table("instruments")
    op.drop_index("ix_executor_devices_status", table_name="executor_devices")
    op.drop_table("executor_devices")
    op.drop_index("ix_domain_events_event_time", table_name="domain_events")
    op.drop_index("ix_domain_events_entity_sequence", table_name="domain_events")
    op.drop_index("ix_domain_events_correlation", table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_index("ix_audit_logs_resource_occurred", table_name="audit_logs")
    op.drop_index("ix_audit_logs_correlation", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
