"""m03_market_data_watchlists

Revision ID: 0003_m03
Revises: 0002_m02
Create Date: 2026-07-15 11:09:22.881179
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003_m03"
down_revision: str | None = "0002_m02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_data_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("supports_realtime", sa.Boolean(), nullable=False),
        sa.Column("supported_timeframes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(supported_timeframes) = 'array' AND jsonb_array_length(supported_timeframes) > 0",
            name=op.f("ck_market_data_sources_supported_timeframes_non_empty_array"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'DISABLED', 'DEGRADED')",
            name=op.f("ck_market_data_sources_status_valid"),
        ),
        sa.CheckConstraint(
            "priority >= 0", name=op.f("ck_market_data_sources_priority_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data_sources")),
        sa.UniqueConstraint("source_code", name="uq_market_data_sources_source_code"),
    )
    op.create_index(
        "ix_market_data_sources_priority", "market_data_sources", ["priority"], unique=False
    )
    op.create_index(
        "ix_market_data_sources_status", "market_data_sources", ["status"], unique=False
    )
    op.create_table(
        "instrument_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_symbol", sa.String(length=128), nullable=False),
        sa.Column("external_exchange", sa.String(length=64), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(external_symbol)) > 0",
            name=op.f("ck_instrument_mappings_external_symbol_non_empty"),
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_instrument_mappings_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.id"],
            name=op.f("fk_instrument_mappings_source_id_market_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument_mappings")),
        sa.UniqueConstraint(
            "source_id", "external_symbol", name="uq_instrument_mappings_source_symbol"
        ),
        sa.UniqueConstraint(
            "source_id", "instrument_id", name="uq_instrument_mappings_source_instrument"
        ),
    )
    op.create_index(
        "ix_instrument_mappings_instrument", "instrument_mappings", ["instrument_id"], unique=False
    )
    op.create_index(
        "ix_instrument_mappings_source", "instrument_mappings", ["source_id"], unique=False
    )
    op.create_table(
        "market_bars",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("timeframe", sa.String(length=32), nullable=False),
        sa.Column("adjustment_type", sa.String(length=32), nullable=False),
        sa.Column("bar_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("vwap", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("open_interest", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quality_status", sa.String(length=32), nullable=False),
        sa.Column(
            "quality_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "adjustment_type IN ('NONE', 'FORWARD', 'BACKWARD')",
            name=op.f("ck_market_bars_adjustment_type_valid"),
        ),
        sa.CheckConstraint(
            "quality_status IN ('NORMAL', 'DELAYED', 'INCOMPLETE', 'INVALID', 'UNKNOWN')",
            name=op.f("ck_market_bars_quality_status_valid"),
        ),
        sa.CheckConstraint(
            "timeframe IN ('MINUTE_1', 'MINUTE_5', 'MINUTE_15', 'MINUTE_30', 'MINUTE_60', 'DAY_1', 'WEEK_1', 'MONTH_1')",
            name=op.f("ck_market_bars_timeframe_valid"),
        ),
        sa.CheckConstraint(
            "amount IS NULL OR amount >= 0", name=op.f("ck_market_bars_amount_non_negative")
        ),
        sa.CheckConstraint(
            "high >= open AND high >= close AND high >= low",
            name=op.f("ck_market_bars_high_not_below_ohlc"),
        ),
        sa.CheckConstraint(
            "low <= open AND low <= close AND low <= high",
            name=op.f("ck_market_bars_low_not_above_ohlc"),
        ),
        sa.CheckConstraint(
            "open > 0 AND high > 0 AND low > 0 AND close > 0",
            name=op.f("ck_market_bars_ohlc_positive"),
        ),
        sa.CheckConstraint(
            "open_interest IS NULL OR open_interest >= 0",
            name=op.f("ck_market_bars_open_interest_non_negative"),
        ),
        sa.CheckConstraint("volume >= 0", name=op.f("ck_market_bars_volume_non_negative")),
        sa.CheckConstraint("vwap IS NULL OR vwap > 0", name=op.f("ck_market_bars_vwap_positive")),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_market_bars_instrument_id_instruments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.id"],
            name=op.f("fk_market_bars_source_id_market_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_bars")),
        sa.UniqueConstraint(
            "instrument_id",
            "source_id",
            "timeframe",
            "adjustment_type",
            "bar_time",
            name="uq_market_bars_identity",
        ),
    )
    op.create_index(
        "ix_market_bars_instrument_source_timeframe_time",
        "market_bars",
        ["instrument_id", "source_id", "timeframe", sa.literal_column("bar_time DESC")],
        unique=False,
    )
    op.create_index(
        "ix_market_bars_instrument_timeframe_time",
        "market_bars",
        ["instrument_id", "timeframe", sa.literal_column("bar_time DESC")],
        unique=False,
    )
    op.create_index(
        "ix_market_bars_quality_received",
        "market_bars",
        ["quality_status", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_market_bars_source_received", "market_bars", ["source_id", "received_at"], unique=False
    )
    op.create_table(
        "market_sync_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=32), nullable=False),
        sa.Column("adjustment_type", sa.String(length=32), nullable=False),
        sa.Column("requested_symbols", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_received", sa.Integer(), nullable=False),
        sa.Column("total_inserted", sa.Integer(), nullable=False),
        sa.Column("total_updated", sa.Integer(), nullable=False),
        sa.Column("total_rejected", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.String(length=1000), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "adjustment_type IN ('NONE', 'FORWARD', 'BACKWARD')",
            name=op.f("ck_market_sync_runs_adjustment_type_valid"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(requested_symbols) = 'array'",
            name=op.f("ck_market_sync_runs_requested_symbols_array"),
        ),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'SUCCEEDED', 'PARTIALLY_SUCCEEDED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_market_sync_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "timeframe IN ('MINUTE_1', 'MINUTE_5', 'MINUTE_15', 'MINUTE_30', 'MINUTE_60', 'DAY_1', 'WEEK_1', 'MONTH_1')",
            name=op.f("ck_market_sync_runs_timeframe_valid"),
        ),
        sa.CheckConstraint(
            "trigger_type IN ('MANUAL', 'CLI', 'SCHEDULED', 'SYSTEM')",
            name=op.f("ck_market_sync_runs_trigger_type_valid"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name=op.f("ck_market_sync_runs_completion_not_early"),
        ),
        sa.CheckConstraint(
            "error_summary IS NULL OR length(error_summary) <= 1000",
            name=op.f("ck_market_sync_runs_error_summary_length"),
        ),
        sa.CheckConstraint(
            "total_received >= 0 AND total_inserted >= 0 AND total_updated >= 0 AND total_rejected >= 0",
            name=op.f("ck_market_sync_runs_counters_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["market_data_sources.id"],
            name=op.f("fk_market_sync_runs_source_id_market_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_sync_runs")),
    )
    op.create_index(
        "ix_market_sync_runs_correlation", "market_sync_runs", ["correlation_id"], unique=False
    )
    op.create_index(
        "ix_market_sync_runs_source_started",
        "market_sync_runs",
        ["source_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "ix_market_sync_runs_status_started",
        "market_sync_runs",
        ["status", "started_at"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_watchlist_items_watchlist_id_watchlists"), "watchlist_items", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_watchlist_items_watchlist_id_watchlists"),
        "watchlist_items",
        "watchlists",
        ["watchlist_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("uq_watchlists_name", "watchlists", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_watchlists_name", "watchlists", type_="unique")
    op.drop_constraint(
        op.f("fk_watchlist_items_watchlist_id_watchlists"), "watchlist_items", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_watchlist_items_watchlist_id_watchlists"),
        "watchlist_items",
        "watchlists",
        ["watchlist_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_index("ix_market_sync_runs_status_started", table_name="market_sync_runs")
    op.drop_index("ix_market_sync_runs_source_started", table_name="market_sync_runs")
    op.drop_index("ix_market_sync_runs_correlation", table_name="market_sync_runs")
    op.drop_table("market_sync_runs")
    op.drop_index("ix_market_bars_source_received", table_name="market_bars")
    op.drop_index("ix_market_bars_quality_received", table_name="market_bars")
    op.drop_index("ix_market_bars_instrument_timeframe_time", table_name="market_bars")
    op.drop_index("ix_market_bars_instrument_source_timeframe_time", table_name="market_bars")
    op.drop_table("market_bars")
    op.drop_index("ix_instrument_mappings_source", table_name="instrument_mappings")
    op.drop_index("ix_instrument_mappings_instrument", table_name="instrument_mappings")
    op.drop_table("instrument_mappings")
    op.drop_index("ix_market_data_sources_status", table_name="market_data_sources")
    op.drop_index("ix_market_data_sources_priority", table_name="market_data_sources")
    op.drop_table("market_data_sources")
    # ### end Alembic commands ###
